### ISSUE TITLE
Test failure on FreeBSD

### ISSUE THREAD

**Issue by eserte** [plicease/App-Prove-Plugin-TermTableStty#1]
On all my FreeBSD smokers (9 .. 13):
```
    # Failed test at t/app_prove_plugin_termtablestty.t line 24.
    # +-----+----+-------+
    # | GOT | OP | CHECK |
    # +-----+----+-------+
    # | 0   | eq | 140   |
    # +-----+----+-------+

# Failed test 'not already set'
# at t/app_prove_plugin_termtablestty.t line 26.
t/app_prove_plugin_termtablestty.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 
```
Tests pass on my Linux smokers.

**Comment by eserte** [comment]
Still happens with 0.02. Reason is probably that corpus/bin/stty requires `/bin/bash` which is never there on FreeBSD (and other *BSD) systems --- if bash is installed, then it's usually located in `/usr/local/bin/bash`. Better to use `/bin/sh` instead, or maybe even better, a perl script.

**Comment by eserte** [comment]
This seems to fix it:
```
diff --git a/corpus/bin/stty b/corpus/bin/stty
index 67c1a1f..fb314bc 100755
--- a/corpus/bin/stty
+++ b/corpus/bin/stty
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 if [ "x$1" == "xsize" ]; then
   echo "77 140"
```

**Comment by plicease** [comment]
Problem with a Perl script is that you still need to know the correct shebang for it to work which is different everywhere too :) I'll go with changing it to `sh` for now.  Last revision was actually to weed out the MSWin32 results, thanks for commenting to remind me of this it is an easy fix.

**Comment by plicease** [comment]
Should be good in version `0.02`.  Please let me know if you fined otherwise.
